// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skyyszkqkpftgqjarstc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNreXlzemtxa3BmdGdxamFyc3RjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5Nzc5OTEsImV4cCI6MjA3NzU1Mzk5MX0.myY4nJMTQoPFE41UBhHdHtzz6upGp_pu8bSJ8KpiZYo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});